// pages/blog/index.vue
<template>
    <navbar></navbar>
    <main>
      <header class="header-spacer-small">
         <div class="flex-box-left">
            <h1 class="text-white"><i class="bi bi-newspaper"></i> News</h1>
            <p class="header-subtitle">The Latest Cubix News</p>
            <div id="news"></div>
         </div>
      </header>
   </main>
   <CFooter></CFooter>
</template>

<script setup>
// Fetch Blogs
</script>

// src/routes/blog/+page.svelte
<script>    
    import { Newspaper } from "svelte-bootstrap-icons";
 </script>

<header class="header-spacer-small">
    <div class="flex-box-left">
       <h1 class="text-white"><Newspaper/> News</h1>
       <p class="header-subtitle">The Latest Cubix News</p>
       <div id="news"></div>
    </div>
 </header>
